import { expect, test } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import { readFile } from 'node:fs/promises'

test('Uberとロケットナウを1回の稼働として精算・再編集する', async ({ page }, info) => {
  test.setTimeout(60_000)
  await page.clock.install({ time: new Date('2026-10-08T22:00:00+09:00') })
  await page.goto('#records')
  await page.getByRole('button', { name: /過去の稼働をまとめて入力/ }).click()
  await page.getByLabel('出発（自宅を出た時刻）', { exact: true }).fill('2026-10-08T18:00')
  await page.getByLabel('帰宅', { exact: true }).fill('2026-10-08T21:00')
  await page.getByLabel('基本報酬', { exact: true }).fill('4000')
  await page.getByLabel('チップ', { exact: true }).fill('200')
  await page.getByLabel('確定ボーナス', { exact: true }).fill('500')
  await page.getByRole('button', { name: '＋ サービスを追加', exact: true }).click()
  const uber = page.getByRole('group', { name: 'Uber Eats', exact: true })
  const rocket = page.getByRole('group', { name: 'ロケットナウ', exact: true })
  await uber.getByLabel('完了件数', { exact: true }).fill('5')
  await page.getByRole('button', { name: '精算を保存', exact: true }).click()
  await expect(page.getByText('各サービスの基本報酬（0円も可）を入力してください')).toBeVisible()
  await rocket.getByLabel('基本報酬', { exact: true }).fill('3000')
  await rocket.getByLabel('チップ', { exact: true }).fill('100')
  await rocket.getByLabel('確定ボーナス', { exact: true }).fill('600')
  await rocket.getByLabel('その他の調整（±）', { exact: true }).fill('-100')
  await rocket.getByLabel('完了件数', { exact: true }).fill('4')
  await page.getByRole('button', { name: '経費を追加', exact: true }).click()
  await page.getByLabel('金額', { exact: true }).fill('200')
  await expect(page.locator('.settlement-result')).toContainText('8,100円')
  await expect(page.locator('.settlement-result')).toContainText('2,700円')
  await expect(rocket.getByLabel('サービス', { exact: true }).locator('option[value="uber"]')).toHaveCount(0)
  for (const colorScheme of ['light', 'dark'] as const) {
    await page.emulateMedia({ colorScheme })
    for (const width of [320, 390, 844, 1280]) {
      await page.setViewportSize({ width, height: width === 844 ? 390 : 844 })
      expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
    }
    await page.setViewportSize({ width: 390, height: 844 })
    await page.screenshot({ path: info.outputPath(`multi-service-${colorScheme}.png`), fullPage: true })
    expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()).violations.filter(v => v.impact === 'serious' || v.impact === 'critical')).toEqual([])
  }
  await page.getByRole('button', { name: '下書き保存', exact: true }).click()
  await expect(page.locator('.record-item')).toBeVisible()
  await page.reload()
  await page.locator('.record-item').click()
  await expect(rocket.getByLabel('基本報酬', { exact: true })).toHaveValue('3000')
  await page.getByRole('button', { name: '精算を保存', exact: true }).click()
  await expect(page.locator('.record-item')).toContainText('ロケットナウ')
  await expect(page.locator('.record-item')).toContainText('Uber Eats')
  await expect(page.locator('.record-item')).toHaveCount(1)
  await page.locator('.record-item').click()
  page.once('dialog', dialog => dialog.dismiss())
  await rocket.getByRole('button', { name: 'このサービスを外す' }).click()
  await expect(rocket).toBeVisible()
  await rocket.getByLabel('基本報酬', { exact: true }).fill('3200')
  await page.getByRole('button', { name: '精算を保存', exact: true }).click()
  await expect(page.locator('.record-item')).toContainText('8,300円')
  await page.getByRole('link', { name: '分析', exact: true }).click()
  await expect(page.locator('.app-main')).toContainText('8,300円')
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'この期間の記録をCSVで書き出す' }).click()
  const download = await downloadPromise
  const csv = await readFile((await download.path())!, 'utf8')
  expect(csv).toContain('ロケットナウ 基本報酬')
  expect(csv).toContain('4000,200,500,0,5')
  expect(csv).toContain('3200,100,600,-100,4')
})
