import { expect, test } from '@playwright/test'

test('4つのメニューから未精算を再開し、明暗・縦横・拡大でも保存できる', async ({ page }, testInfo) => {
  await page.goto('#home')
  await expect(page.getByRole('navigation').getByRole('link')).toHaveText(['今日', '計画', '記録', '分析'])
  await page.getByRole('link', { name: '設定', exact: true }).click()
  await expect(page.getByRole('heading', { name: '設定', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '記録', exact: true }).click()
  await page.getByRole('button', { name: /過去の稼働をまとめて入力/ }).click()
  await page.getByLabel('出発（自宅を出た時刻）', { exact: true }).fill('2026-10-07T18:00')
  await page.getByLabel('帰宅', { exact: true }).fill('2026-10-07T21:00')
  await page.getByLabel('基本報酬', { exact: true }).fill('6600')
  await page.getByLabel('チップ', { exact: true }).fill('180')
  await page.getByLabel('確定ボーナス', { exact: true }).fill('400')
  await page.getByRole('button', { name: '下書き保存', exact: true }).click()
  await page.getByRole('button', { name: '未精算・下書き（1）', exact: true }).click()
  await page.locator('.record-item').click()
  await expect(page.getByLabel('帰宅', { exact: true })).toBeHidden()
  await expect(page.locator('.settlement-summary')).toContainText('7,180円')
  for (const colorScheme of ['light', 'dark'] as const) {
    await page.emulateMedia({ colorScheme })
    for (const [width, height] of [[320, 700], [390, 844], [844, 390], [1280, 800]]) {
      await page.setViewportSize({ width: width!, height: height! })
      expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBe(0)
      await expect(page.getByRole('button', { name: '精算を保存', exact: true })).toBeInViewport()
      if (width === 390) await page.screenshot({ path: testInfo.outputPath(`settlement-${colorScheme}.png`), fullPage: true })
    }
  }
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: '精算を保存', exact: true }).click()
  await expect(page.getByText('未精算・下書きはありません。')).toBeVisible()
  await page.getByRole('button', { name: 'すべて', exact: true }).click()
  await expect(page.locator('.record-item')).toContainText('7,180円')
})

test('稼働中の主な操作は52px以上。昼下がりは休憩の比較が折りたたみの外で自動で開く', async ({ page }) => {
  // 昼下がり（注文が少なめの時間）
  await page.clock.install({ time: new Date('2026-10-07T14:00:00+09:00') })
  await page.goto('#home')
  const depart = page.getByRole('button', { name: '自宅を出発' })
  expect((await depart.boundingBox())!.height).toBeGreaterThanOrEqual(52)
  await depart.click()
  const start = page.getByRole('button', { name: 'レンタル開始' })
  expect((await start.boundingBox())!.height).toBeGreaterThanOrEqual(52)
  await start.click()
  const back = page.getByRole('button', { name: '返却を記録' })
  await expect(back).toBeVisible()
  expect((await back.boundingBox())!.height).toBeGreaterThanOrEqual(52)
  // 料金の上限・乗る長さごとの料金は畳んだまま、休憩の比較は開いて見える
  await expect(page.locator('details.rental-details')).not.toHaveAttribute('open', '')
  await expect(page.getByText(/☕ 休憩するなら/)).toBeVisible()
  await expect(page.getByText(/☕ 休憩するなら/).locator('xpath=..')).toHaveAttribute('open', '')
})

test('デザイン案「今日」：頭に日付と保存場所、時計と配達終了予定、レンタル料金と次回の課金、精算ボタンはメニューのすぐ上', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-07T18:00:00+09:00') })
  await page.goto('#home')
  await expect(page.locator('.app-header')).toContainText('10月7日(水)')
  await expect(page.locator('.app-header')).toContainText('端末内で記録')
  await page.getByRole('button', { name: '自宅を出発' }).click()
  await page.getByRole('button', { name: 'レンタル開始' }).click()
  await page.clock.fastForward('02:18:00')
  await expect(page.getByRole('heading', { name: '今日の稼働 稼働中' })).toBeVisible()
  await expect(page.getByLabel('出発から2時間18分')).toHaveText('02:18')
  await expect(page.locator('.today-return')).toContainText('配達終了予定')
  const rental = page.getByRole('region', { name: /レンタル料金/ })
  await expect(rental).toContainText('次の課金まで')
  await expect(rental).toContainText(/次回 \+\d+円/)
  await expect(rental.getByRole('button', { name: '↩ 返却を記録' })).toBeVisible()
  // ほかの判断のたすけは畳んである
  await expect(page.getByRole('heading', { name: /終了までの見通し/ })).toBeHidden()
  // 精算のボタンは、どこまで下げても画面の中（メニューのすぐ上）
  const settle = page.getByRole('button', { name: '帰宅して精算' })
  await expect(settle).toBeInViewport()
  await page.mouse.wheel(0, 2000)
  await expect(settle).toBeInViewport()
  const nav = await page.getByRole('navigation', { name: 'メニュー' }).boundingBox()
  expect((await settle.boundingBox())!.y + 52).toBeLessThanOrEqual(nav!.y + 1)
})

test('デザイン案「帰宅後の精算」：時間の帯・売上・経費・今日の利益と実質時給・精算を保存と下書き保存', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-07T18:00:00+09:00') })
  await page.goto('#home')
  await page.getByRole('button', { name: '自宅を出発' }).click()
  await page.getByRole('button', { name: 'レンタル開始' }).click()
  await page.clock.fastForward('03:00:00')
  await page.getByRole('button', { name: '帰宅して精算' }).click()
  await expect(page.getByRole('heading', { name: '今日の精算' })).toBeVisible()
  await expect(page.locator('details.time-band > summary')).toContainText(/出発 18:00 → 帰宅 21:00\s*3時間/)
  await page.getByLabel('基本報酬', { exact: true }).fill('6800')
  await page.getByLabel('チップ', { exact: true }).fill('380')
  await page.getByLabel('レンタル実請求', { exact: true }).fill('1760')
  await page.getByRole('button', { name: '経費を追加' }).click()
  await page.getByLabel('金額', { exact: true }).fill('200')
  // 6,800 + 380 − 1,760 − 200 = 5,220円、3時間で 1,740円/時
  const result = page.locator('.settlement-result')
  await expect(result).toContainText('今日の利益')
  await expect(result).toContainText('5,220円')
  await expect(result).toContainText('1,740円')
  await expect(page.getByRole('button', { name: '下書き保存' })).toBeVisible()
  await page.getByRole('button', { name: '精算を保存' }).click()
  await expect(page.locator('.list-item').first()).toContainText('確定')
})

test('デザイン案「週間計画」：予定／提案の切り替え、おすすめの提案のカードと日ごとの行、下に固定の「この提案を予定に追加」', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-10-05T12:00:00+09:00') })
  await page.goto('#plan')
  const setup = page.getByRole('form', { name: '計画の初期設定' })
  await setup.getByLabel('計画に使う週の時間', { exact: true }).fill('12')
  await setup.getByLabel('計画の目標時給', { exact: true }).fill('1000')
  await setup.getByLabel('利用する自転車・料金', { exact: true }).selectOption({ label: '自分の自転車・月額サブスク' })
  await setup.getByLabel('働ける時間帯', { exact: true }).selectOption('side-night')
  await setup.getByRole('button', { name: '条件を保存して提案を見る' }).click()
  await expect(page.getByRole('heading', { name: '週間計画' })).toBeVisible()
  await expect(page.locator('.plan-conditions')).toContainText('週の上限 12時間')
  await expect(page.getByRole('tab', { name: '提案' })).toHaveAttribute('aria-selected', 'true')
  await expect(page.getByRole('heading', { name: '💡 おすすめの提案' })).toBeVisible()
  await expect(page.locator('.proposal-big')).toContainText(/\d+時間 \/ \d+日/)
  await expect(page.getByRole('list', { name: '作戦の日ごと' }).getByRole('listitem').first()).toContainText('時間')
  const add = page.getByRole('button', { name: 'この提案を予定に追加' })
  await expect(add).toBeInViewport()
  await add.click()
  await expect(page.getByText(/🧭 \d+つの候補枠を入れました/)).toBeVisible()
  // 予定に切り替えると、稼働の量と7日の帯
  await page.getByRole('tab', { name: '予定' }).click()
  await expect(page.getByRole('heading', { name: /この週の稼働/ })).toBeVisible()
  await expect(page.getByRole('list', { name: 'この週の予定' })).toBeVisible()
})


test('入力済みの精算の補足欄も閉じられ、別の金額を入力しても閉じた状態を保つ', async ({ page }) => {
  await page.goto('#records')
  await page.getByRole('button', { name: /過去の稼働をまとめて入力/ }).click()
  await page.locator('details.extras > summary').click()
  await page.getByLabel('完了件数', { exact: true }).fill('5')
  await page.locator('details.extras > summary').click()
  await page.getByLabel('基本報酬', { exact: true }).fill('3000')
  await expect(page.getByLabel('完了件数', { exact: true })).toBeHidden()
  await expect(page.locator('.app-header')).not.toContainText('保存済み')
  await page.locator('details.extras > summary').click()
  await expect(page.getByLabel('完了件数', { exact: true })).toHaveValue('5')
})
